// Canned ingestion responses (OpenAI). Used when:
//   - OPENAI_API_KEY is missing (local demo without a key)
//   - the live call times out or errors
//
// Fixtures, matched against the uploaded filename:
//   * `fake_contract_products_with_logo.pdf`  → 8 clean ACME rows (all
//     active). Mirrors the C-numbers picked in plan.md Phase 6.
//   * `sample-contract-messy.pdf`             → 6 rows, 4 of which land in
//     review (null price, price range, missing unit, merged line).
//   * `catalog-wuerth.pdf`                    → 10 clean Würth rows.
//   * `catalog-sfs.pdf`                       → 10 clean SFS rows.
//   * `catalog-gerber-vogt.pdf`               → 10 clean Gerber-Vogt rows.
//   (the three catalogs are generated by scripts/author-catalog-pdfs.ts.)
//
// If the filename matches none, a small one-row generic response is
// returned so the UI still has something to render.

import type { IngestResponse } from "../schema";

const ACME_SUPPLIER = "ACME Bauzulieferung AG";

export const CANNED_CLEAN_ACME: IngestResponse = {
  supplier_name: ACME_SUPPLIER,
  rows: [
    {
      name: "Schraube TX20 4x40",
      supplier_sku: "ACME-C001",
      unit: "Stk",
      unit_price: 0.09,
      product_group: "fasteners",
      hazardous: false,
      confidence: 0.97,
    },
    {
      name: "Kabelbinder 200mm",
      supplier_sku: "ACME-C013",
      unit: "Stk",
      unit_price: 0.07,
      product_group: "electrical",
      hazardous: false,
      confidence: 0.95,
    },
    {
      name: "Arbeitshandschuhe Gr.9",
      supplier_sku: "ACME-C019",
      unit: "Paar",
      unit_price: 2.7,
      product_group: "ppe",
      hazardous: false,
      confidence: 0.96,
    },
    {
      name: "Malervlies",
      supplier_sku: "ACME-C025",
      unit: "Rolle",
      unit_price: 19.5,
      product_group: "covers_tape",
      hazardous: false,
      confidence: 0.94,
    },
    {
      name: "Markierspray rot",
      supplier_sku: "ACME-C029",
      unit: "Dose",
      unit_price: 7.8,
      product_group: "paint",
      hazardous: true,
      confidence: 0.93,
    },
    {
      name: "Bohrer 10mm",
      supplier_sku: "ACME-C035",
      unit: "Stk",
      unit_price: 5.6,
      product_group: "tools",
      hazardous: false,
      confidence: 0.96,
    },
    {
      name: "Wasserwaage 60cm",
      supplier_sku: "ACME-C046",
      unit: "Stk",
      unit_price: 19.2,
      product_group: "tools",
      hazardous: false,
      confidence: 0.95,
    },
    {
      name: "Baustellenlampe LED",
      supplier_sku: "ACME-C056",
      unit: "Stk",
      unit_price: 31,
      product_group: "electrical",
      hazardous: false,
      confidence: 0.94,
    },
  ],
};

export const CANNED_MESSY_ACME: IngestResponse = {
  supplier_name: ACME_SUPPLIER,
  rows: [
    {
      name: "Bauschaum XL 750 ml",
      supplier_sku: "ACME-200",
      unit: "Dose",
      unit_price: null, // "auf Anfrage"
      product_group: "sealants",
      hazardous: true,
      confidence: 0.42,
    },
    {
      name: "Putzeimer Mehrzweck 15L",
      supplier_sku: "ACME-201",
      unit: "Stk",
      unit_price: null, // "5 – 8 CHF" range, can't pick a value
      product_group: "cleaning_chemicals",
      hazardous: false,
      confidence: 0.52,
    },
    {
      name: "Reinigungstücher Industrie",
      supplier_sku: "ACME-202",
      unit: null, // missing unit on the source row
      unit_price: 12.4,
      product_group: "cleaning_chemicals",
      hazardous: false,
      confidence: 0.45,
    },
    {
      name: "Schraube TX25 6x80 / passender Dübel 8mm",
      supplier_sku: "ACME-203",
      unit: "Stk",
      unit_price: 0.32,
      product_group: "fasteners",
      hazardous: false,
      confidence: 0.55,
    },
    {
      name: "Klebeband universal 50mm",
      supplier_sku: "ACME-204",
      unit: "Rolle",
      unit_price: 6.1,
      product_group: "covers_tape",
      hazardous: false,
      confidence: 0.92,
    },
    {
      name: "Schutzhandschuh Cut-5 Gr.10",
      supplier_sku: "ACME-205",
      unit: "Paar",
      unit_price: 3.6,
      product_group: "ppe",
      hazardous: false,
      confidence: 0.91,
    },
  ],
};

// Three additional clean supplier catalogs (all rows active), generated by
// scripts/author-catalog-pdfs.ts. Mirror the PDFs exactly so a missing/slow
// OpenAI key still ingests them. C-materials only — no blocklist terms.

export const CANNED_CATALOG_WUERTH: IngestResponse = {
  supplier_name: "Würth AG",
  rows: [
    { name: "Spanplattenschraube TX20 4.0x40", supplier_sku: "WUR-1001", unit: "Stk", unit_price: 0.08, product_group: "fasteners", hazardous: false, confidence: 0.97 },
    { name: "Spanplattenschraube TX25 5.0x60", supplier_sku: "WUR-1002", unit: "Stk", unit_price: 0.12, product_group: "fasteners", hazardous: false, confidence: 0.97 },
    { name: "Nylon-Dübel 8mm", supplier_sku: "WUR-1015", unit: "Stk", unit_price: 0.06, product_group: "fasteners", hazardous: false, confidence: 0.96 },
    { name: "Montagekleber MS-Polymer 290ml", supplier_sku: "WUR-2003", unit: "Kartusche", unit_price: 8.9, product_group: "sealants", hazardous: false, confidence: 0.95 },
    { name: "Silikon sanitär transparent 310ml", supplier_sku: "WUR-2010", unit: "Kartusche", unit_price: 6.4, product_group: "sealants", hazardous: false, confidence: 0.95 },
    { name: "Nitril-Einweghandschuhe Gr.M (Box 100)", supplier_sku: "WUR-3005", unit: "Box", unit_price: 9.8, product_group: "ppe", hazardous: false, confidence: 0.96 },
    { name: "Schutzbrille klar", supplier_sku: "WUR-3012", unit: "Stk", unit_price: 4.2, product_group: "ppe", hazardous: false, confidence: 0.95 },
    { name: "Gewebeband silber 50mm x 50m", supplier_sku: "WUR-4001", unit: "Rolle", unit_price: 7.5, product_group: "covers_tape", hazardous: false, confidence: 0.96 },
    { name: "Malerkrepp 30mm x 50m", supplier_sku: "WUR-4008", unit: "Rolle", unit_price: 2.3, product_group: "covers_tape", hazardous: false, confidence: 0.95 },
    { name: "Bremsenreiniger 500ml", supplier_sku: "WUR-5002", unit: "Dose", unit_price: 4.9, product_group: "cleaning_chemicals", hazardous: true, confidence: 0.93 },
  ],
};

export const CANNED_CATALOG_SFS: IngestResponse = {
  supplier_name: "SFS Group AG",
  rows: [
    { name: "Holzschraube TX30 6.0x80", supplier_sku: "SFS-100", unit: "Stk", unit_price: 0.18, product_group: "fasteners", hazardous: false, confidence: 0.97 },
    { name: "Tellerkopfschraube TX40 8.0x120", supplier_sku: "SFS-110", unit: "Stk", unit_price: 0.35, product_group: "fasteners", hazardous: false, confidence: 0.97 },
    { name: "Blechschraube 4.8x19", supplier_sku: "SFS-150", unit: "Stk", unit_price: 0.05, product_group: "fasteners", hazardous: false, confidence: 0.96 },
    { name: "Schlagdübel 6x40", supplier_sku: "SFS-160", unit: "Stk", unit_price: 0.09, product_group: "fasteners", hazardous: false, confidence: 0.96 },
    { name: "Gipskartonschraube 3.5x35 (Box 1000)", supplier_sku: "SFS-170", unit: "Box", unit_price: 6.2, product_group: "fasteners", hazardous: false, confidence: 0.95 },
    { name: "Unterlegscheibe M8 (Btl. 100)", supplier_sku: "SFS-180", unit: "Beutel", unit_price: 3.1, product_group: "fasteners", hazardous: false, confidence: 0.95 },
    { name: "Bit-Set TX 25-tlg", supplier_sku: "SFS-300", unit: "Set", unit_price: 12.5, product_group: "tools", hazardous: false, confidence: 0.95 },
    { name: "Bohrer HSS 6mm", supplier_sku: "SFS-310", unit: "Stk", unit_price: 2.1, product_group: "tools", hazardous: false, confidence: 0.96 },
    { name: "Maßband 5m", supplier_sku: "SFS-320", unit: "Stk", unit_price: 6.8, product_group: "tools", hazardous: false, confidence: 0.96 },
    { name: "Cuttermesser 18mm + 5 Klingen", supplier_sku: "SFS-330", unit: "Stk", unit_price: 4.4, product_group: "tools", hazardous: false, confidence: 0.95 },
  ],
};

export const CANNED_CATALOG_GERBER_VOGT: IngestResponse = {
  supplier_name: "Gerber-Vogt AG",
  rows: [
    { name: "Warnweste gelb Kl.2", supplier_sku: "GV-401", unit: "Stk", unit_price: 5.9, product_group: "ppe", hazardous: false, confidence: 0.96 },
    { name: "Schutzhelm weiss", supplier_sku: "GV-402", unit: "Stk", unit_price: 11.5, product_group: "ppe", hazardous: false, confidence: 0.96 },
    { name: "Gehörschutzstöpsel (Box 200)", supplier_sku: "GV-410", unit: "Box", unit_price: 18.0, product_group: "ppe", hazardous: false, confidence: 0.95 },
    { name: "Industriereiniger Konzentrat 1L", supplier_sku: "GV-501", unit: "Flasche", unit_price: 7.2, product_group: "cleaning_chemicals", hazardous: true, confidence: 0.93 },
    { name: "Mikrofasertuch (Pack 10)", supplier_sku: "GV-510", unit: "Pack", unit_price: 6.5, product_group: "cleaning_chemicals", hazardous: false, confidence: 0.95 },
    { name: "Abfallsack 120L (Rolle 25)", supplier_sku: "GV-520", unit: "Rolle", unit_price: 9.4, product_group: "cleaning_chemicals", hazardous: false, confidence: 0.95 },
    { name: "Kabelbinder 300mm schwarz (Btl. 100)", supplier_sku: "GV-601", unit: "Beutel", unit_price: 4.8, product_group: "electrical", hazardous: false, confidence: 0.96 },
    { name: "Isolierband schwarz 19mm", supplier_sku: "GV-610", unit: "Rolle", unit_price: 1.9, product_group: "electrical", hazardous: false, confidence: 0.96 },
    { name: "LED-Baustrahler 30W", supplier_sku: "GV-620", unit: "Stk", unit_price: 38.0, product_group: "electrical", hazardous: false, confidence: 0.94 },
    { name: "Markierspray fluoreszierend orange 500ml", supplier_sku: "GV-701", unit: "Dose", unit_price: 6.9, product_group: "paint", hazardous: true, confidence: 0.93 },
  ],
};

export const CANNED_GENERIC: IngestResponse = {
  supplier_name: "Unbekannter Lieferant",
  rows: [
    {
      name: "Mustereintrag — bitte prüfen",
      supplier_sku: "GENERIC-001",
      unit: null,
      unit_price: null,
      product_group: null,
      hazardous: false,
      confidence: 0.3,
    },
  ],
};

export function cannedIngestFor(filename: string | undefined | null): IngestResponse {
  const lower = (filename ?? "").toLowerCase();
  if (lower.includes("messy")) return CANNED_MESSY_ACME;
  if (lower.includes("fake_contract") || lower.includes("logo")) {
    return CANNED_CLEAN_ACME;
  }
  if (lower.includes("wuerth")) return CANNED_CATALOG_WUERTH;
  if (lower.includes("sfs")) return CANNED_CATALOG_SFS;
  if (lower.includes("gerber")) return CANNED_CATALOG_GERBER_VOGT;
  return CANNED_GENERIC;
}
