// Tiny HTTPS proxy in front of `next dev` so mobile browsers can use the
// microphone (getUserMedia requires a secure context — localhost is allowed
// but a LAN IP is not).
//
// Usage:
//   1. Run `npm run dev` in one terminal (HTTP server on :3000).
//   2. Run `node scripts/https-proxy.mjs` here (HTTPS on :3443).
//   3. On the phone open `https://<your-lan-ip>:3443`.
//      Accept the "self-signed certificate" warning once.
//
// Certs were generated by mkcert (see ~/Library/Caches/mkcert/) into
// `certificates/`. They cover localhost, 127.0.0.1, ::1, 0.0.0.0 and the
// LAN IP captured at generation time.

import { readFileSync } from "node:fs";
import { createServer as createHttpsServer } from "node:https";
import { request as httpRequest } from "node:http";

const HTTPS_PORT = Number(process.env.HTTPS_PORT) || 3443;
const HTTP_TARGET_HOST = "127.0.0.1";
const HTTP_TARGET_PORT = Number(process.env.HTTP_TARGET_PORT) || 3000;

const tlsOptions = {
  key: readFileSync("certificates/localhost-key.pem"),
  cert: readFileSync("certificates/localhost.pem"),
};

function forwardRequest(req, res) {
  // Server Actions CSRF: Next.js compares the `Origin` header (e.g.
  // https://192.168.168.75:3443) against the `Host` / `x-forwarded-host`.
  // If we rewrote `host` to 127.0.0.1:3000 here, Next would see a mismatch
  // and refuse with "Invalid Server Actions request" (500). So we preserve
  // the client's `host` and pass explicit x-forwarded-* headers — that's
  // what proxies are supposed to do.
  const clientHost = req.headers.host ?? `${HTTP_TARGET_HOST}:${HTTP_TARGET_PORT}`;
  const headers = {
    ...req.headers,
    host: clientHost,
    "x-forwarded-host": clientHost,
    "x-forwarded-proto": "https",
    "x-forwarded-for":
      (req.headers["x-forwarded-for"]
        ? `${req.headers["x-forwarded-for"]}, `
        : "") + (req.socket?.remoteAddress ?? "127.0.0.1"),
  };

  const proxyReq = httpRequest(
    {
      hostname: HTTP_TARGET_HOST,
      port: HTTP_TARGET_PORT,
      method: req.method,
      path: req.url,
      headers,
    },
    (proxyRes) => {
      res.writeHead(proxyRes.statusCode ?? 502, proxyRes.headers);
      proxyRes.pipe(res);
    },
  );
  proxyReq.on("error", (err) => {
    console.error("[https-proxy] upstream error:", err.message);
    if (!res.headersSent) res.writeHead(502, { "content-type": "text/plain" });
    res.end("Upstream Next dev server is not reachable on :3000.\n");
  });
  req.pipe(proxyReq);
}

const server = createHttpsServer(tlsOptions, forwardRequest);

// Next.js dev uses websockets for HMR. Forward the upgrade.
server.on("upgrade", (req, clientSocket, head) => {
  const upstream = httpRequest({
    hostname: HTTP_TARGET_HOST,
    port: HTTP_TARGET_PORT,
    method: req.method,
    path: req.url,
    headers: { ...req.headers, host: `${HTTP_TARGET_HOST}:${HTTP_TARGET_PORT}` },
  });
  upstream.on("upgrade", (_upstreamRes, upstreamSocket, upstreamHead) => {
    clientSocket.write(
      "HTTP/1.1 101 Switching Protocols\r\n" +
        Object.entries(_upstreamRes.headers)
          .map(([k, v]) => `${k}: ${v}`)
          .join("\r\n") +
        "\r\n\r\n",
    );
    if (upstreamHead && upstreamHead.length) clientSocket.write(upstreamHead);
    if (head && head.length) upstreamSocket.write(head);
    upstreamSocket.pipe(clientSocket);
    clientSocket.pipe(upstreamSocket);
  });
  upstream.on("error", () => clientSocket.destroy());
  upstream.end();
});

server.listen(HTTPS_PORT, "0.0.0.0", () => {
  console.log(`HTTPS proxy listening on https://0.0.0.0:${HTTPS_PORT}`);
  console.log(`  → forwards to http://${HTTP_TARGET_HOST}:${HTTP_TARGET_PORT}`);
});
